# Generated by Django 5.0.1 on 2024-02-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_user_resultlearning_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
